export const TYPES = {
  READ_ALL_USER: 'READ_ALL_USER_FROM_DB',
  READ_ONE_USER: 'READ_ONE_FROM_DB',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  NO_DATA: 'NO_DATA',
}
